language: python

python:
  - '2.7'

script:
  - cd ./link_tester
  - pip install -r ./requirements.txt
  - python ./link_test.py https://www.github.com
  - cd ../http_code_checker
  - pip install -r ./requirements.txt
  - python ./main.py https://www.github.com
